### ISSUE TITLE
Examples / Tests?

### ISSUE THREAD

**Issue by mgallagher** [tizoc/ppx_pgsql#2]
These would be appreciated 👍

**Comment by tizoc** [comment]
I'm sorry @mgallagher! I never saw this until someone else opened a new issue yesterday. Right now my OCaml install is broken after an operating system upgrade, I will add an example program once I'm able to fix it.

But for the basic setup for Lwt, take a look at my reply to #3

**Comment by tizoc** [comment]
Added an example here https://github.com/tizoc/ppx_pgsql/blob/master/example/todo_lwt.ml

**Comment by mgallagher** [comment]
Much appreciated @tizoc, thanks for the update 👍
